clone/urls.py
#CLONE URLS.PY
from django.urls import path
# as auth_views because: don't mix it with our views below
from django.contrib.auth import views as auth_views
from . import views

app_name = "clone"

urlpatterns = [
	path("login/",
		auth_views.LoginView.as_view(template_name='clone/login.html'),
		name='login'),
	path("logout/",auth_views.LogoutView.as_view(),name='logout'),
	path("signup/",views.SignUp.as_view(),name='signup'),
]

clone_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('clone.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

groups/urls.py
#GROUPS URL.PY
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
	path('',views.ListGroups.as_view(),name='all'),
	path('new/',views.CreateGroup.as_view(),name='create'),
	path('post/in/<str:slug>/',views.SingleGroup.as_view(),name='single'),
	path('join/<str:slug>/',views.JoinGroup.as_view(), name='join'),
	path('leave/<str:slug>/',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('',views.PostsList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create_post'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='for_user'),
    path('delete/<int:pk>/',views.DeleteViwe.as_view(),name='delete'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),

]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# GROUPS MODELS.PY FILE
# Create your models here.

#import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
	name = models.CharField(max_length=255,unique=True)
	slug = models.SlugField(allow_unicode=True,unique=True)
	description = models.TextField(blank=True,default='')
	description_html = models.TextField(blank=True,editable=False,default='')
	members = models.ManyToManyField(User,through='GroupMember')

	def __str__(self):
		return self.name

	def save(self,*args,**kwargs):
		self.slug = slugify(self.name)
#		self.description_html = misaka.html(self.description_html)
		super().save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse("groups:single",kwargs={'slug':self.slug})



class GroupMember(models.Model):
	group = models.ForeignKey(Group,related_name='memberships',on_delete='CASCADE')
	user = models.ForeignKey(User,related_name='user_groups',on_delete='CASCADE')

	def __str__(self):
		return self.user.username

	class Meta:
		unique_together = ('group','user')

groups/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib import messages

# Create your views here.
# GROUPS viev.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
										PermissionRequiredMixin)

from . import models
from django.urls import reverse
from django.views import generic
from .models import Group,GroupMember

class CreateGroup(LoginRequiredMixin,generic.CreateView):
	fields = ('name', 'description')
	model = Group

class SingleGroup(generic.DetailView):
	model = Group

class ListGroups(generic.ListView):
	model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

	def get_redirect_url(self,*args,**kwargs):
		return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

	def get(self,request,*args,**kwargs):
		group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

		try:
			GroupMember.objects.create(user=self.request.user,group=group)
		except IntegrityError:
			messages.warning(self.request,'Warning! Already a member')
		else:
			messages.success(self.request,'You are now a member!')
		return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

	def get_redirect_url(self,*args,**kwargs):
		return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

	def get(self,request,*args,**kwargs):
		#group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

		try:
			membership = models.GroupMember.objects.filter(
			user = self.request.user,
			group__slug=self.kwargs.get('slug')
			).get()
		except models.GroupMember.DoesNotExist:
			messages.warning(self.request, 'Sorry, you are not in this group!')
		else:
			membership.delete()
			messages.success(self.request,"You have left the group!", request)
		return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<div class="row">
			{% block pregroup %}{% endblock %}
			{% block group_content %}{% endblock %}
			{% block postgroup %}{% endblock %}
		</div>
	</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

	<div>
		<h1>Group: <strong>"{{ group.name }}"</strong></h1>
		<h2>{{ group.members.count }} members.</h2>
	</div>

	<div class="col">
		{% if user in group.members.all %}
			<a href="{% url 'groups:leave' slug=group.slug %}"
			class="btn btn-lg btn-fill btn-warning">Leave</a>
		{% else %}
			<a href="{% url 'groups:join' slug=group.slug %}"
			class="btn btn-lg btn-fill btn-warning">Join</a>
		{% endif %}
	</div>

{% endblock %}

{% block group_content %}
	<div class='col-md-8'>
		{% if group.posts.count == 0 %}
			<h3>No posts in this group yet!</h3>
		{% else %}
			{% for post in group.posts.all %}
				{% include "posts/_post.html" %}
			{% endfor %}
		{% endif %}
	</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block group_content %}
	<h4>Create a new Group!</h4>
	<form action="{% url 'groups:create' %}" method="POST" id="groupForm">
		{% csrf_token %}
		{% bootstrap_form form show_label=False %}
		<input type="submit" value="Create" class="btn btn-large btn-primary">
	</form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block precontent %}
	<div class="col-md-4">
		<div class="content">
			{% if user.is_authenticated %}
				<h3>Welcome back,
					<a href="{% url 'post:for_user' username=user.username %}">
					@{{ user.username }}</a>
				!</h3>
			{% endif %}
			<h3>Groups</h3>
			<p>Welcome to the groups page!</p>
		</div>
		{% if user.is_authenticated %}
			<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
			Create New Group</a>
		{% endif %}
	</div>
{% endblock %}

{% block group_content %}
	<div class="col-md-8">
		<div class="list-group">
			{% for group in object_list %}
				<a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
					<h3 class="title list-group-item-heading">{{ group.name }}</h3>
					<div class="list-group-item-text container-fluid">
						{{group.description|safe}}
						<div class="row">
							<div class="col-md-4">
								<span class="bage">{{ group.members.count }}</span>
								member{{ group.members.count|pluralize }}
							</div>
							<div class="col-md-4">
								<span class="bage">{{ group.posts.count }}</span>
								post{{ group.posts.count|pluralize }}
							</div>
						</div>
					</div>
				</a>
			{% endfor %}
		</div>
	</div>
{% endblock %}