clone/urls.py
#CLONE URLS.PY
from django.urls import path
# as auth_views because: don't mix it with our views below
from django.contrib.auth import views as auth_views
from . import views

app_name = "clone"

urlpatterns = [
	path("login/",
		auth_views.LoginView.as_view(template_name='clone/login.html'),
		name='login'),
	path("logout/",auth_views.LogoutView.as_view(),name='logout'),
	path("signup/",views.SignUp.as_view(),name='signup'),
]

clone_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('clone.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

groups/urls.py
#GROUPS URL.PY
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
	path('',views.ListGroups.as_view(),name='all'),
	path('new/',views.CreateGroup.as_view(),name='create'),
	path('post/in/<str:slug>/',views.SingleGroup.as_view(),name='single'),
	path('join/<str:slug>/',views.JoinGroup.as_view(), name='join'),
	path('leave/<str:slug>/',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('',views.PostsList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create_post'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='for_user'),
    path('delete/<int:pk>/',views.DeleteViwe.as_view(),name='delete'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Star Social</title>
	<!-- BOOTSTRAP4 -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<!-- BS4 JS -->
	<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="{% static 'simplesocial/js/master.js' %}" type="text/javascript" ></script>
	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Noto+Serif+KR&display=swap" rel="stylesheet">
	<!-- font-family: 'Noto Serif KR', serif; -->
	<!-- Own stylesheet -->
	<link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
</head>
<body>
	<nav class="navbar mynav" role="navigation" id="navbar">
		<div class="container">
			<a class="navbar-brand mynav" href="{% url 'home' %}">Start Social</a>
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a class="nav-ul" href="{% url 'posts:create_post' %}">Post</a></li>
					<li><a class="nav-ul" href="{% url 'groups:all' %}">Group</a></li>
					<li><a class="nav-ul" href="{% url 'groups:create' %}">Create Group</a></li>
					<li><a class="nav-ul" href="{% url 'clone:logout' %}">Log Out</a></li>
				{% else %}
					<li><a class="nav-ul" href="{% url 'groups:all' %}">Groups</a></li>
					<li><a class="nav-ul" href="{% url 'clone:login' %}">Login</a></li>
					<li><a class="nav-ul" href="{% url 'clone:signup' %}">Sign Up</a></li>
					<li><a class="nav-ul" href=""></a></li>
				{% endif %}
			</ul>
		</div>
	</nav>
	<div class="container mycontent">
		{% block content %}

		{% endblock %}
	</div>
	<div class="stars-back">
		<div class="stars"></div>
		<div class="twinkling"></div>
		<div class="clouds"></div>
	</div>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
	<h1>Welcome to Star Social!</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
	<h1>You are now logined in!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
	<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}