clone/urls.py
#CLONE URLS.PY
from django.urls import path
# as auth_views because: don't mix it with our views below
from django.contrib.auth import views as auth_views
from . import views

app_name = "clone"

urlpatterns = [
	path("login/",
		auth_views.LoginView.as_view(template_name='clone/login.html'),
		name='login'),
	path("logout/",auth_views.LogoutView.as_view(),name='logout'),
	path("signup/",views.SignUp.as_view(),name='signup'),
]

clone_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('clone.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('',views.PostsList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create_post'),
    path('by/<str:username>/',views.UserPosts.as_view(),name='for_user'),
    path('delete/<int:pk>/',views.DeleteViwe.as_view(),name='delete'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),

]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

#import misaka

from groups.models import Group

# POST MODELS>PY
# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
	user = models.ForeignKey(User,related_name='posts',on_delete='CASCADE')
	created_at = models.DateTimeField(auto_now=True)
	message = models.TextField()
	message_html = models.TextField(editable=False)
	group = models.ForeignKey(Group,related_name='posts',null=True,blank=True,on_delete='CASCADE')

	def __str__(self):
		return self.message

	def save(self,*args,**kwargs):
		#self.message_html = misaka(self.message)
		super().save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('posts:single',kwargs={'username':self.user.username,
												'pk':self.pk})

	class Meta:
		ordering = ['-created_at']
		unique_together = ['user','message']

posts/views.py
#POSTS VIEVS.PY
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models
from . import forms


User = get_user_model()
# Create your views here.

class PostsList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeleteViwe(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args,**kwargs)

posts/templates/posts/_post.html
<div class="list-group-item">
    <h4 class="row">
    <span class="username">
        <a href="{% url 'posts:for_user' username=post.user.username %}">By @{{post.user.username}}</a>
    </span>
    <time class="time">
      <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">at {{post.created_at}}</a>
    </time>
  </h4>




  <!-- need <h2>{{post.message_html|safe}}</h2> -->
  <p>{{post.message|safe}}</p>

    <div class="media-footer">
    {% if user.is_authenticated and post.user == user %}
      <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple" aria-hidden='true'>
        <span class="text-dengar icon-lable">Delete post</span>
      </a>
    {% endif %}
  </div>





</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
  <div class="posts-page">
    <div class="container">
      <div class="row">
        {% block prepost %}{% endblock %}
        {% block post_content %}{% endblock %}
        {% block post_post %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
  <h2>Delete?</h2>
  <div class="posts">
    {% include 'posts/_post.html'  with post=object hide_delete=True %}
  </div>
  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger btn-large">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
    class="btn btn-simple btn-large btn-default">Cancel</a>
  </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
  <div class="col-md-8">
    {% include 'posts/_post.html' %}
  </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
  <h3>Create a new post:</h3>
  <form id="postForm" action="{% url 'posts:create_post' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form show_label=False %}
    <input type="submit" value="Post" class="btn btn-primary btn-large">
  </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title">Your Groups</h5>
          <ul class="list-unstyled">
            {% for member_group in get_user_groups %}
              <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=member_group.group.slug %}">{{group.name}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endif %}
    <div class="card card-with-shadow">
      <div class="content">
        <h5 class="title">All Groups</h5>
        <ul class="list-unstyled">
          {% for other_group in get_other_groups %}
            <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{other_group.name}}</a></li>
          {% endfor %}
        </ul>
    </div>
    </div>
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include 'posts/_post.html' %}
    {% endfor %}
  </div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
  <div class="col-md-3">
    <h1>@{{post_user.username}}</h1>
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}